### PR TITLE
countdown timer

### PR DESCRIPTION
**Pull request by alpha-oss**

### CODE REVIEW

**Comment by TechGuideExpress** [comment]
Thank you for contributing. Happy Coding.

**Comment by alpha-oss** [comment]
I wanted to know if that hactoberfest label was given or not on this pull request .

**Comment by alpha-oss** [comment]
If the labels are added little faster it would be better .

**Comment by alpha-oss** [comment]
@TechGuideExpress If the labels are added little faster it would be better

**Pull request merged**
